FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY dist dist

# These variables are used by DefaultIdentityProvider. Only non-production
# credentials should be stored and accessed this way
ENV AZURE_TENANT_ID=<redacted>
ENV AZURE_CLIENT_ID=<redacted>
ENV AZURE_CLIENT_SECRET=<redacted>
CMD ["node", "/usr/src/app/dist/app.js"]


